function sim_results = sim_operation_linear(signal, control, ...
                                            state, bw_int, opt)
% SIM_OPERATION_LINEAR specialized simulation for signal type 'linear'
%
% SIM_OPERATION_LINEAR applies the control strategy to the signal at a
% specific cut. It is a specialized function of SIM_OPERATION for signals
% of type 'linear'.
%
% SIM_RESULTS = SIM_OPERATION_LINEAR(SIGNAL, CONTROL, STATE, BW_INT, OPT)
% where SIGNAL is a signal structure generated by GEN_SIGNAL, CONTROL is a
% signal specific control strategy generated by the parent function, as
% well as STATE. BW_INT is the backward integral optained during the
% dimensioning process of the function HYBRID_PAIR. OPT is an options
% structure obtained through HYBRIDSET.
%
% SIM_RESULTS is a structure with the following fields:
%   .powers
%       .base   fhandle, function of time
%       .peak   fhandle, function of time
%   .energies
%       .base   fhandle, function of time
%       .peak   fhandle, function of time
%   .state      fhandle, function of time, control state
% This structure will be complemented by the parent function.
%
% See also SIM_OPERATION, CONTROL_FACTORY, HYBRID_PAIR

% TODO implement this function
% Deferred, signal changed at beginning of 'sim_operation' (as the other
% variables are also dependend on the signal type)

sigfhandle = linear_to_fhandle(signal, opt);

sim_results = sim_operation_fhandle(sigfhandle, control, state, bw_int, opt);

end
